# Generated by Django 5.2.8 on 2025-11-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qa", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="user",
            field=models.UUIDField(help_text="UUID of author", unique=True),
        ),
    ]
