# Generated by Django 5.2.8 on 2025-11-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qa", "0002_alter_answer_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="user",
            field=models.UUIDField(help_text="UUID of author"),
        ),
    ]
